### ISSUE TITLE
Simple test parsing int sometimes

### ISSUE THREAD

**Issue by wdavidw** [maxogden/csv-spectrum#15]
I dont understand [this commit](https://github.com/maxogden/csv-spectrum/commit/ec45e96a79661d7bd87f6becbb845b30f11accde). Note, it also break [my tests](https://github.com/wdavidw/node-csv-parse/commit/fb9ba540ab11ab4b31a8cc3ce14668207c2f582f).

I cant find any reason why you did this :(

**Comment by maxogden** [comment]
cc @morganrallen

@wdavidw sorry about that, merged without considering the semver case. Happy to revert, but also want to address @morganrallen's original issue. Anyone have ideas?

**Comment by morganrallen** [comment]
Here's the original issue, #13 
The test data was incomplete because it didn't include a Number.

Revert it, bump version and reapply?

**Comment by wdavidw** [comment]
Not sure numbers shall be treated as a special character by default. In [csv-parse](https://github.com/wdavidw/node-csv-parse), you'll need to specify an addition option "auto_parse" so that number would receive a particular treatment.

**Comment by wdavidw** [comment]
by the way, @maxogden, i like your dat projet. I love the versioning/cloning part as well as the binary support (now in latest git). I'm personnaly looking for the same kind of tool but with a more json like structure in opposite to tabular data. An API similar to [baobab](https://github.com/Yomguithereal/baobab).

**Comment by morganrallen** [comment]
Not sure what else to say on this. My understanding of csv-spectrum is to provide a test data set for handling conversions to and from CSV. It's didn't include a number in the data set, therefor it was incomplete.

Your test doesn't handle a number, because there wasn't one for you to test against. This change exposed that bug in your test. But it should not have, if the version was bumped correctly.

So my suggestion remains, revert the change, bump to 0.0.4, reapply the change and release as 0.1.0.

**Comment by wdavidw** [comment]
What i dont understand in this commit is why only "b" is numeric. Either "a", "b" and "c" shall have their value casted to numeric or none of them. Whichever option, i'll adjust my test.

**Comment by morganrallen** [comment]
Nothing short of I just needed a number and simple seemed as good as any a place to put it. In hindsight maybe this should have been renamed strings.js and a more robost numbers.js added.

**Comment by maxogden** [comment]
@morganrallen good idea, I think having a number type is necessary. I'll put the test case in a separate file.

**Comment by maxogden** [comment]
Actually, sorry, upon further thought I don't think having a number makes sense. JSON surely supports it, but I don't think it makes sense to expect CSV to differentiate between String and Number JS types. IMO everything in CSV is a string, and casting types is up to the user (via metadata or some other method than CSV). Or you can put the result of JSON.stringify into a cell.

I think its easier to just focus on CSV -> JSON parsing and not claim we do JSON -> CSV -> JSON fully since that gets opinionated.

Sorry for the back and forth. I just published 1.0.0 which is the same as 0.2.0 was :D
